### ISSUE TITLE
1.19.4

### ISSUE THREAD

**Issue by srnyx** [Crec0/BetterDarkMode#8]

**Comment by Crec0** [comment]
Hey, I dont really know if this mod is worth updating to 1.19.4 or any future minecraft updates. The entire purpose of the mod's existence has been replaced by much better shader based mods. Even the vanilla tweaks dark mod texture pack (which is what initially made me create this mod) now uses shader instead of hardcoded values. I dont think this mod has a purpose now and I will probably archive it in upcoming days
Thanks for using it :)

**Comment by srnyx** [comment]
> Hey, I dont really know if this mod is worth updating to 1.19.4 or any future minecraft updates. The entire purpose of the mod's existence has been replaced by much better shader based mods. Even the vanilla tweaks dark mod texture pack (which is what initially made me create this mod) now uses shader instead of hardcoded values. I dont think this mod has a purpose now and I will probably archive it in upcoming days Thanks for using it :)

Aw dang, yeah now that I think about it [Darkomizer](https://darkomizer.com/) (what I use) actually has a Text field now, just used to using this mod I guess lmao, thank you!
